services:
  - type: web
    name: clubfutebol-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
